/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#c8daff",
        "tertiary-fixed-dim": "#bfc8d0",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006b5b",
        "tertiary-container": "#576068",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "secondary-fixed": "#78f8dd",
        "primary": "#00478d",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed": "#141d23",
        "on-secondary-fixed": "#00201a",
        "error-container": "#ffdad6",
        "secondary-container": "#78f8dd",
        "primary-fixed-dim": "#a9c7ff",
        "primary-fixed": "#d6e3ff",
        "error": "#ba1a1a",
        "surface-tint": "#005db6",
        "secondary-fixed-dim": "#59dbc1",
        "on-surface-variant": "#424752",
        "surface-dim": "#d9dadb",
        "surface-container-high": "#e7e8e9",
        "surface-variant": "#e1e3e4",
        "outline": "#727783",
        "on-tertiary-fixed-variant": "#3f484f",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed-variant": "#005144",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fa",
        "primary-container": "#005eb8",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#00468c",
        "on-primary-fixed": "#001b3d",
        "on-secondary-container": "#007261",
        "on-tertiary-container": "#d1dae4",
        "outline-variant": "#c2c6d4",
        "on-primary": "#ffffff",
        "tertiary": "#404850",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed": "#dbe4ed",
        "on-background": "#191c1d",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "inverse-primary": "#a9c7ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "xxl": "48px",
        "gutter": "24px",
        "lg": "24px",
        "margin-desktop": "40px",
        "base": "4px",
        "xs": "4px",
        "xl": "32px",
        "md": "16px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "data-mono": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}

