// <auto-generated />
using System;
using ClinicAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAssist.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616105107_RemovedQRHas")]
    partial class RemovedQRHas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAssist.Models.Assistant", b =>
                {
                    b.Property<int>("assistant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assistant_id"));

                    b.Property<int>("clinic_id")
                        .HasColumnType("int");

                    b.Property<string>("contact_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("assistant_id");

                    b.HasIndex("clinic_id");

                    b.HasIndex("user_id");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("ClinicAssist.Models.Assistant_Permission", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<int>("assistant_id")
                        .HasColumnType("int");

                    b.Property<bool>("can_create_prescriptions")
                        .HasColumnType("bit");

                    b.Property<bool>("can_upload_reports")
                        .HasColumnType("bit");

                    b.Property<bool>("can_view_prescriptions")
                        .HasColumnType("bit");

                    b.Property<bool>("can_view_reports")
                        .HasColumnType("bit");

                    b.HasKey("permission_id");

                    b.HasIndex("assistant_id");

                    b.ToTable("Assistant_Permissions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Clinic", b =>
                {
                    b.Property<int>("clinic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clinic_id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clinic_qr_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clinic_id");

                    b.HasIndex("doctor_id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("ClinicAssist.Models.Clinic_Medicine", b =>
                {
                    b.Property<int>("medicine_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("medicine_id"));

                    b.Property<int>("clinic_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("medicine_id");

                    b.HasIndex("clinic_id");

                    b.ToTable("Clinic_Medicines");
                });

            modelBuilder.Entity("ClinicAssist.Models.Doctor", b =>
                {
                    b.Property<int>("doctor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("doctor_id"));

                    b.Property<string>("specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("doctor_id");

                    b.HasIndex("user_id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ClinicAssist.Models.Document", b =>
                {
                    b.Property<int>("document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("document_id"));

                    b.Property<string>("document_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("origin_clinic_id")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("uploaded_by_user_id")
                        .HasColumnType("int");

                    b.HasKey("document_id");

                    b.HasIndex("origin_clinic_id");

                    b.HasIndex("patient_id");

                    b.HasIndex("uploaded_by_user_id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ClinicAssist.Models.Document_Access_Permission", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<int>("clinic_id")
                        .HasColumnType("int");

                    b.Property<int>("document_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_granted")
                        .HasColumnType("bit");

                    b.HasKey("permission_id");

                    b.HasIndex("clinic_id");

                    b.HasIndex("document_id");

                    b.ToTable("Document_Access_Permissions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Patient", b =>
                {
                    b.Property<int>("patient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patient_id"));

                    b.Property<string>("blood_group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("patient_id");

                    b.HasIndex("user_id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicAssist.Models.Patient_Clinic_Registration", b =>
                {
                    b.Property<int>("registration_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("registration_id"));

                    b.Property<int>("clinic_id")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("registered_at")
                        .HasColumnType("datetime2");

                    b.HasKey("registration_id");

                    b.HasIndex("clinic_id");

                    b.HasIndex("patient_id");

                    b.ToTable("Patient_Clinic_Registrations");
                });

            modelBuilder.Entity("ClinicAssist.Models.Prescription", b =>
                {
                    b.Property<int>("prescription_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("prescription_id"));

                    b.Property<int>("clinic_id")
                        .HasColumnType("int");

                    b.Property<int>("created_by_user_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("date_issued")
                        .HasColumnType("datetime2");

                    b.Property<int>("doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.HasKey("prescription_id");

                    b.HasIndex("clinic_id");

                    b.HasIndex("created_by_user_id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("patient_id");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Prescription_Item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("item_id"));

                    b.Property<string>("dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("medicine_id")
                        .HasColumnType("int");

                    b.Property<int>("prescription_id")
                        .HasColumnType("int");

                    b.HasKey("item_id");

                    b.HasIndex("medicine_id");

                    b.HasIndex("prescription_id");

                    b.ToTable("Prescription_Items");
                });

            modelBuilder.Entity("ClinicAssist.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("contact_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClinicAssist.Models.Assistant", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "clinic")
                        .WithMany("Assistants")
                        .HasForeignKey("clinic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.User", "user")
                        .WithMany("Assistants")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("clinic");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ClinicAssist.Models.Assistant_Permission", b =>
                {
                    b.HasOne("ClinicAssist.Models.Assistant", "assistant")
                        .WithMany("Assistant_Permissions")
                        .HasForeignKey("assistant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assistant");
                });

            modelBuilder.Entity("ClinicAssist.Models.Clinic", b =>
                {
                    b.HasOne("ClinicAssist.Models.Doctor", "doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("doctor");
                });

            modelBuilder.Entity("ClinicAssist.Models.Clinic_Medicine", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "clinic")
                        .WithMany("Clinic_Medicines")
                        .HasForeignKey("clinic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic");
                });

            modelBuilder.Entity("ClinicAssist.Models.Doctor", b =>
                {
                    b.HasOne("ClinicAssist.Models.User", "user")
                        .WithMany("Doctors")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ClinicAssist.Models.Document", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "origin_clinic")
                        .WithMany()
                        .HasForeignKey("origin_clinic_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicAssist.Models.Patient", "patient")
                        .WithMany("Documents")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.User", "uploaded_by_user")
                        .WithMany()
                        .HasForeignKey("uploaded_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("origin_clinic");

                    b.Navigation("patient");

                    b.Navigation("uploaded_by_user");
                });

            modelBuilder.Entity("ClinicAssist.Models.Document_Access_Permission", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "clinic")
                        .WithMany()
                        .HasForeignKey("clinic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.Document", "document")
                        .WithMany("Document_Access_Permissions")
                        .HasForeignKey("document_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic");

                    b.Navigation("document");
                });

            modelBuilder.Entity("ClinicAssist.Models.Patient", b =>
                {
                    b.HasOne("ClinicAssist.Models.User", "user")
                        .WithMany("Patients")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ClinicAssist.Models.Patient_Clinic_Registration", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "clinic")
                        .WithMany("Patient_Clinic_Registrations")
                        .HasForeignKey("clinic_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.Patient", "patient")
                        .WithMany("Patient_Clinic_Registrations")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("ClinicAssist.Models.Prescription", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic", "clinic")
                        .WithMany()
                        .HasForeignKey("clinic_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.User", "created_by_user")
                        .WithMany()
                        .HasForeignKey("created_by_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.Doctor", "doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.Patient", "patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("clinic");

                    b.Navigation("created_by_user");

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("ClinicAssist.Models.Prescription_Item", b =>
                {
                    b.HasOne("ClinicAssist.Models.Clinic_Medicine", "medicine")
                        .WithMany()
                        .HasForeignKey("medicine_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicAssist.Models.Prescription", "prescription")
                        .WithMany("Prescription_Items")
                        .HasForeignKey("prescription_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medicine");

                    b.Navigation("prescription");
                });

            modelBuilder.Entity("ClinicAssist.Models.Assistant", b =>
                {
                    b.Navigation("Assistant_Permissions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Clinic", b =>
                {
                    b.Navigation("Assistants");

                    b.Navigation("Clinic_Medicines");

                    b.Navigation("Patient_Clinic_Registrations");
                });

            modelBuilder.Entity("ClinicAssist.Models.Doctor", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Document", b =>
                {
                    b.Navigation("Document_Access_Permissions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Patient", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Patient_Clinic_Registrations");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ClinicAssist.Models.Prescription", b =>
                {
                    b.Navigation("Prescription_Items");
                });

            modelBuilder.Entity("ClinicAssist.Models.User", b =>
                {
                    b.Navigation("Assistants");

                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
